// Code generated by protoc-gen-go.
// source: interact.proto
// DO NOT EDIT!

/*
Package interact is a generated protocol buffer package.

It is generated from these files:
	interact.proto

It has these top-level messages:
	ServerStatus
	ClientStatus
	Token
	Quiz
	Session
	Req
	Question
	Answer
	Response
	Status
*/
package interact

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type QuizState int32

const (
	Quiz_DEMO_NOT_TAKEN QuizState = 0
	Quiz_DEMO_STARTED   QuizState = 1
	Quiz_TEST_NOT_TAKEN QuizState = 2
	Quiz_TEST_STARTED   QuizState = 3
	Quiz_TEST_FINISHED  QuizState = 4
)

var QuizState_name = map[int32]string{
	0: "DEMO_NOT_TAKEN",
	1: "DEMO_STARTED",
	2: "TEST_NOT_TAKEN",
	3: "TEST_STARTED",
	4: "TEST_FINISHED",
}
var QuizState_value = map[string]int32{
	"DEMO_NOT_TAKEN": 0,
	"DEMO_STARTED":   1,
	"TEST_NOT_TAKEN": 2,
	"TEST_STARTED":   3,
	"TEST_FINISHED":  4,
}

func (x QuizState) String() string {
	return proto.EnumName(QuizState_name, int32(x))
}
func (QuizState) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{3, 0} }

type ServerStatus struct {
	TimeLeft string `protobuf:"bytes,1,opt,name=timeLeft" json:"timeLeft,omitempty"`
	Status   string `protobuf:"bytes,2,opt,name=status" json:"status,omitempty"`
}

func (m *ServerStatus) Reset()                    { *m = ServerStatus{} }
func (m *ServerStatus) String() string            { return proto.CompactTextString(m) }
func (*ServerStatus) ProtoMessage()               {}
func (*ServerStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type ClientStatus struct {
	CurrQuestion string `protobuf:"bytes,1,opt,name=currQuestion" json:"currQuestion,omitempty"`
	Token        string `protobuf:"bytes,2,opt,name=token" json:"token,omitempty"`
}

func (m *ClientStatus) Reset()                    { *m = ClientStatus{} }
func (m *ClientStatus) String() string            { return proto.CompactTextString(m) }
func (*ClientStatus) ProtoMessage()               {}
func (*ClientStatus) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type Token struct {
	Id string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
}

func (m *Token) Reset()                    { *m = Token{} }
func (m *Token) String() string            { return proto.CompactTextString(m) }
func (*Token) ProtoMessage()               {}
func (*Token) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type Quiz struct {
}

func (m *Quiz) Reset()                    { *m = Quiz{} }
func (m *Quiz) String() string            { return proto.CompactTextString(m) }
func (*Quiz) ProtoMessage()               {}
func (*Quiz) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

type Session struct {
	Id    string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	State QuizState `protobuf:"varint,2,opt,name=state,enum=interact.QuizState" json:"state,omitempty"`
}

func (m *Session) Reset()                    { *m = Session{} }
func (m *Session) String() string            { return proto.CompactTextString(m) }
func (*Session) ProtoMessage()               {}
func (*Session) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

type Req struct {
	Repeat bool   `protobuf:"varint,1,opt,name=repeat" json:"repeat,omitempty"`
	Sid    string `protobuf:"bytes,2,opt,name=sid" json:"sid,omitempty"`
	Token  string `protobuf:"bytes,3,opt,name=token" json:"token,omitempty"`
}

func (m *Req) Reset()                    { *m = Req{} }
func (m *Req) String() string            { return proto.CompactTextString(m) }
func (*Req) ProtoMessage()               {}
func (*Req) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

type Question struct {
	Id         string    `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Str        string    `protobuf:"bytes,2,opt,name=str" json:"str,omitempty"`
	Options    []*Answer `protobuf:"bytes,3,rep,name=options" json:"options,omitempty"`
	IsMultiple bool      `protobuf:"varint,4,opt,name=isMultiple" json:"isMultiple,omitempty"`
	Positive   float32   `protobuf:"fixed32,6,opt,name=positive" json:"positive,omitempty"`
	Negative   float32   `protobuf:"fixed32,7,opt,name=negative" json:"negative,omitempty"`
	Totscore   float32   `protobuf:"fixed32,8,opt,name=totscore" json:"totscore,omitempty"`
}

func (m *Question) Reset()                    { *m = Question{} }
func (m *Question) String() string            { return proto.CompactTextString(m) }
func (*Question) ProtoMessage()               {}
func (*Question) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *Question) GetOptions() []*Answer {
	if m != nil {
		return m.Options
	}
	return nil
}

type Answer struct {
	Id  string `protobuf:"bytes,1,opt,name=id" json:"id,omitempty"`
	Str string `protobuf:"bytes,2,opt,name=str" json:"str,omitempty"`
}

func (m *Answer) Reset()                    { *m = Answer{} }
func (m *Answer) String() string            { return proto.CompactTextString(m) }
func (*Answer) ProtoMessage()               {}
func (*Answer) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

type Response struct {
	Qid   string   `protobuf:"bytes,1,opt,name=qid" json:"qid,omitempty"`
	Aid   []string `protobuf:"bytes,2,rep,name=aid" json:"aid,omitempty"`
	Sid   string   `protobuf:"bytes,3,opt,name=sid" json:"sid,omitempty"`
	Token string   `protobuf:"bytes,4,opt,name=token" json:"token,omitempty"`
}

func (m *Response) Reset()                    { *m = Response{} }
func (m *Response) String() string            { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()               {}
func (*Response) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

type Status struct {
	Status int64 `protobuf:"varint,1,opt,name=status" json:"status,omitempty"`
}

func (m *Status) Reset()                    { *m = Status{} }
func (m *Status) String() string            { return proto.CompactTextString(m) }
func (*Status) ProtoMessage()               {}
func (*Status) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func init() {
	proto.RegisterType((*ServerStatus)(nil), "interact.ServerStatus")
	proto.RegisterType((*ClientStatus)(nil), "interact.ClientStatus")
	proto.RegisterType((*Token)(nil), "interact.Token")
	proto.RegisterType((*Quiz)(nil), "interact.Quiz")
	proto.RegisterType((*Session)(nil), "interact.Session")
	proto.RegisterType((*Req)(nil), "interact.Req")
	proto.RegisterType((*Question)(nil), "interact.Question")
	proto.RegisterType((*Answer)(nil), "interact.Answer")
	proto.RegisterType((*Response)(nil), "interact.Response")
	proto.RegisterType((*Status)(nil), "interact.Status")
	proto.RegisterEnum("interact.QuizState", QuizState_name, QuizState_value)
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion2

// Client API for GruQuiz service

type GruQuizClient interface {
	Authenticate(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Session, error)
	GetQuestion(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Question, error)
	SendAnswer(ctx context.Context, in *Response, opts ...grpc.CallOption) (*Status, error)
	StreamChan(ctx context.Context, opts ...grpc.CallOption) (GruQuiz_StreamChanClient, error)
}

type gruQuizClient struct {
	cc *grpc.ClientConn
}

func NewGruQuizClient(cc *grpc.ClientConn) GruQuizClient {
	return &gruQuizClient{cc}
}

func (c *gruQuizClient) Authenticate(ctx context.Context, in *Token, opts ...grpc.CallOption) (*Session, error) {
	out := new(Session)
	err := grpc.Invoke(ctx, "/interact.GruQuiz/Authenticate", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gruQuizClient) GetQuestion(ctx context.Context, in *Req, opts ...grpc.CallOption) (*Question, error) {
	out := new(Question)
	err := grpc.Invoke(ctx, "/interact.GruQuiz/GetQuestion", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gruQuizClient) SendAnswer(ctx context.Context, in *Response, opts ...grpc.CallOption) (*Status, error) {
	out := new(Status)
	err := grpc.Invoke(ctx, "/interact.GruQuiz/SendAnswer", in, out, c.cc, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gruQuizClient) StreamChan(ctx context.Context, opts ...grpc.CallOption) (GruQuiz_StreamChanClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_GruQuiz_serviceDesc.Streams[0], c.cc, "/interact.GruQuiz/StreamChan", opts...)
	if err != nil {
		return nil, err
	}
	x := &gruQuizStreamChanClient{stream}
	return x, nil
}

type GruQuiz_StreamChanClient interface {
	Send(*ClientStatus) error
	Recv() (*ServerStatus, error)
	grpc.ClientStream
}

type gruQuizStreamChanClient struct {
	grpc.ClientStream
}

func (x *gruQuizStreamChanClient) Send(m *ClientStatus) error {
	return x.ClientStream.SendMsg(m)
}

func (x *gruQuizStreamChanClient) Recv() (*ServerStatus, error) {
	m := new(ServerStatus)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for GruQuiz service

type GruQuizServer interface {
	Authenticate(context.Context, *Token) (*Session, error)
	GetQuestion(context.Context, *Req) (*Question, error)
	SendAnswer(context.Context, *Response) (*Status, error)
	StreamChan(GruQuiz_StreamChanServer) error
}

func RegisterGruQuizServer(s *grpc.Server, srv GruQuizServer) {
	s.RegisterService(&_GruQuiz_serviceDesc, srv)
}

func _GruQuiz_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Token)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GruQuizServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interact.GruQuiz/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GruQuizServer).Authenticate(ctx, req.(*Token))
	}
	return interceptor(ctx, in, info, handler)
}

func _GruQuiz_GetQuestion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Req)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GruQuizServer).GetQuestion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interact.GruQuiz/GetQuestion",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GruQuizServer).GetQuestion(ctx, req.(*Req))
	}
	return interceptor(ctx, in, info, handler)
}

func _GruQuiz_SendAnswer_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Response)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GruQuizServer).SendAnswer(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/interact.GruQuiz/SendAnswer",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GruQuizServer).SendAnswer(ctx, req.(*Response))
	}
	return interceptor(ctx, in, info, handler)
}

func _GruQuiz_StreamChan_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(GruQuizServer).StreamChan(&gruQuizStreamChanServer{stream})
}

type GruQuiz_StreamChanServer interface {
	Send(*ServerStatus) error
	Recv() (*ClientStatus, error)
	grpc.ServerStream
}

type gruQuizStreamChanServer struct {
	grpc.ServerStream
}

func (x *gruQuizStreamChanServer) Send(m *ServerStatus) error {
	return x.ServerStream.SendMsg(m)
}

func (x *gruQuizStreamChanServer) Recv() (*ClientStatus, error) {
	m := new(ClientStatus)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _GruQuiz_serviceDesc = grpc.ServiceDesc{
	ServiceName: "interact.GruQuiz",
	HandlerType: (*GruQuizServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Authenticate",
			Handler:    _GruQuiz_Authenticate_Handler,
		},
		{
			MethodName: "GetQuestion",
			Handler:    _GruQuiz_GetQuestion_Handler,
		},
		{
			MethodName: "SendAnswer",
			Handler:    _GruQuiz_SendAnswer_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StreamChan",
			Handler:       _GruQuiz_StreamChan_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
}

var fileDescriptor0 = []byte{
	// 542 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0x84, 0x54, 0xdd, 0x4e, 0xdb, 0x4c,
	0x14, 0x8c, 0xe3, 0xfc, 0xf8, 0x3b, 0x84, 0x7c, 0x61, 0x85, 0xd2, 0x28, 0x17, 0x15, 0xda, 0xab,
	0x88, 0x8b, 0xa8, 0x4a, 0x79, 0x81, 0x00, 0x2e, 0xa0, 0x96, 0x20, 0x6c, 0xab, 0xb7, 0xc8, 0x0d,
	0x87, 0xb2, 0x6a, 0xb0, 0xcd, 0xee, 0x9a, 0x4a, 0x7d, 0xc6, 0xbe, 0x4a, 0xdf, 0xa1, 0xfb, 0xe7,
	0x9f, 0xa2, 0x4a, 0xbd, 0xdb, 0x33, 0x67, 0x76, 0x32, 0x1e, 0x8f, 0x03, 0x63, 0x96, 0x49, 0xe4,
	0xe9, 0x56, 0x2e, 0x0b, 0x9e, 0xcb, 0x9c, 0x04, 0xd5, 0x4c, 0x4f, 0x61, 0x14, 0x23, 0x7f, 0x41,
	0x1e, 0xcb, 0x54, 0x96, 0x82, 0xcc, 0x21, 0x90, 0xec, 0x09, 0x3f, 0xe1, 0x83, 0x9c, 0x79, 0x47,
	0xde, 0xe2, 0xbf, 0xa8, 0x9e, 0xc9, 0x14, 0x06, 0xc2, 0xb0, 0x66, 0x5d, 0xb3, 0x71, 0x13, 0xbd,
	0x84, 0xd1, 0xd9, 0x8e, 0x61, 0x26, 0x9d, 0x06, 0x85, 0xd1, 0xb6, 0xe4, 0xfc, 0xb6, 0x44, 0x21,
	0x59, 0x9e, 0x39, 0x9d, 0x3f, 0x30, 0x72, 0x08, 0x7d, 0x99, 0x7f, 0xc3, 0xcc, 0x49, 0xd9, 0x81,
	0xbe, 0x81, 0x7e, 0xa2, 0x0f, 0x64, 0x0c, 0x5d, 0x76, 0xef, 0x2e, 0xaa, 0x13, 0xcd, 0xa0, 0x77,
	0x5b, 0xb2, 0x1f, 0xf4, 0x01, 0xfa, 0xfa, 0x47, 0x91, 0x10, 0x18, 0x9f, 0x87, 0xd7, 0x37, 0x77,
	0x9b, 0x9b, 0xe4, 0x2e, 0x59, 0x7f, 0x0c, 0x37, 0x93, 0x0e, 0x99, 0xc0, 0xc8, 0x60, 0x71, 0xb2,
	0x8e, 0x92, 0xf0, 0x7c, 0xe2, 0x69, 0x56, 0x12, 0xc6, 0x49, 0x8b, 0xd5, 0xd5, 0x2c, 0x83, 0x55,
	0x2c, 0x9f, 0x1c, 0xc0, 0xbe, 0x41, 0x3e, 0x5c, 0x6d, 0xae, 0xe2, 0x4b, 0x05, 0xf5, 0x68, 0x08,
	0xc3, 0x18, 0x85, 0xd0, 0x4e, 0x5f, 0x59, 0x21, 0xc7, 0xce, 0x82, 0x71, 0x3e, 0x5e, 0x1d, 0x2e,
	0xeb, 0x6c, 0xb5, 0xc3, 0xa5, 0xd9, 0x45, 0x96, 0xa2, 0x64, 0xfc, 0x08, 0x9f, 0x75, 0x70, 0x1c,
	0x0b, 0x4c, 0x6d, 0xa4, 0x41, 0xe4, 0x26, 0x65, 0xc5, 0x17, 0x4a, 0xdb, 0x46, 0xa0, 0x8f, 0x4d,
	0x2c, 0x7e, 0x3b, 0x96, 0x9f, 0x1e, 0x04, 0x75, 0x72, 0xaf, 0xfd, 0x68, 0x11, 0xc9, 0x6b, 0x11,
	0xc9, 0x95, 0xc3, 0x61, 0x5e, 0x68, 0xae, 0x50, 0x32, 0xfe, 0x62, 0x6f, 0x35, 0x69, 0x3c, 0xae,
	0x33, 0xf1, 0x1d, 0x79, 0x54, 0x11, 0xc8, 0x5b, 0x00, 0x26, 0xae, 0xcb, 0x9d, 0x64, 0xc5, 0x0e,
	0x67, 0x3d, 0x63, 0xaf, 0x85, 0xe8, 0x3e, 0x14, 0xb9, 0x60, 0x92, 0xbd, 0xe0, 0x6c, 0xa0, 0xb6,
	0xdd, 0xa8, 0x9e, 0xf5, 0x2e, 0xc3, 0xaf, 0xa9, 0xd9, 0x0d, 0xed, 0xae, 0x9a, 0x4d, 0x8f, 0x72,
	0x29, 0xb6, 0x39, 0xc7, 0x59, 0x60, 0x77, 0xd5, 0x4c, 0x8f, 0x61, 0x60, 0x6d, 0xfc, 0xfb, 0x59,
	0xe8, 0x67, 0x08, 0x22, 0x14, 0x85, 0xb2, 0x8a, 0x7a, 0xfb, 0x5c, 0xd3, 0xf5, 0x51, 0x23, 0xa9,
	0x09, 0xd0, 0xd7, 0x48, 0xea, 0x14, 0x14, 0xe2, 0xff, 0x25, 0xd2, 0x5e, 0x3b, 0xd2, 0x23, 0x18,
	0xb8, 0xb6, 0x36, 0xad, 0xd6, 0xc2, 0x7e, 0xd5, 0xea, 0xd5, 0x2f, 0x0f, 0x86, 0x17, 0xbc, 0xd4,
	0x2f, 0x95, 0x9c, 0xc0, 0x68, 0x5d, 0xca, 0x47, 0x55, 0x71, 0xb6, 0xd5, 0xed, 0xfb, 0xbf, 0x09,
	0xd4, 0xf4, 0x75, 0x7e, 0xd0, 0x00, 0xae, 0x37, 0xb4, 0x43, 0x56, 0xb0, 0x77, 0x81, 0xb2, 0x7e,
	0x71, 0xfb, 0x0d, 0x47, 0x95, 0x62, 0x4e, 0xda, 0xc5, 0xb1, 0x14, 0x75, 0xe7, 0x04, 0x20, 0xc6,
	0xec, 0xde, 0xe5, 0x43, 0xda, 0x57, 0x6c, 0x0a, 0xf3, 0xd6, 0xcb, 0xb4, 0x4f, 0xa0, 0x6e, 0x9d,
	0xaa, 0x5b, 0x92, 0x63, 0xfa, 0x74, 0xf6, 0x98, 0x66, 0x64, 0xda, 0x30, 0xda, 0xdf, 0xe5, 0x7c,
	0xda, 0x36, 0xd9, 0x7c, 0xf3, 0xb4, 0xb3, 0xf0, 0xde, 0x79, 0x5f, 0x06, 0xe6, 0xaf, 0xe1, 0xfd,
	0xef, 0x00, 0x00, 0x00, 0xff, 0xff, 0x37, 0x3c, 0xd6, 0x38, 0x2c, 0x04, 0x00, 0x00,
}
